import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import Hero from "~/components/Hero";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Organixbio | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="">
        <Header />
        <Hero />
      </main>
    </>
  );
};

export default Home;
