import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import Hero from "~/components/Hero";
import SectionFour from "~/components/SectionFour";
import SectionThree from "~/components/SectionThree";
import SectionTwo from "~/components/SectionTwo";
import { Poppins } from "next/font/google";
import SectionFive from "~/components/SectionFive";
import SectionSix from "~/components/SectionSix";
import SectionSeven from "~/components/SectionSeven";
import Footer from "~/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Organixbio | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={poppins.className}>
        <Header />
        <Hero />
        <SectionTwo />
        <SectionThree />
        <SectionFour />
        <SectionFive />
        <SectionSix />
        <SectionSeven />
        <Footer />
      </main>
    </>
  );
};

export default Home;
